/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main_Pengguna;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static Main_Pengguna.Pemesanan_Tiket.con;
import static Main_Pengguna.Pemesanan_Tiket.st;
import Model_Pengguna.pengguna;

/**
 *
 * @author MiftakhulAziz
 */
public class Riwayat_Pemesanan extends javax.swing.JFrame {
        
         Login log = new Login();
            String usr=log.ambilUsername;
            String pass=log.ambilPassword;
            String kd_usr = log.ambilKodeUser;
            pengguna pm = new pengguna();
            List<pengguna> dataLogin=new ArrayList<>();
            
            Koneksi db = new Koneksi();
            public static Statement st;
            public ResultSet rs;
            private DefaultTableModel ledom ;
    /**
     * Creates new form Riwayat_Pemesanan
     */
    public Riwayat_Pemesanan() {
        initComponents();
        this.ledom = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
            
        };
         tblRiwayat.setModel(ledom);
        
        ledom.addColumn("Tanggal Pemesanan");
        ledom.addColumn("Jadwal Keberangkatan");
        ledom.addColumn("Jam Keberangkatan");
        ledom.addColumn("Plat Bus");
        ledom.addColumn("Nomor Kursi");
        ledom.addColumn("Asal Keberangkatan");
        ledom.addColumn("Tujuan Keberangkatan");
                      
        getData();
        setLocationRelativeTo(null);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRiwayat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        exit3 = new javax.swing.JLabel();
        back1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setPreferredSize(new java.awt.Dimension(810, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(255, 204, 204));
        Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102)));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRiwayat.setBackground(new java.awt.Color(240, 240, 240));
        tblRiwayat.setFont(new java.awt.Font("Ubuntu Condensed", 0, 14)); // NOI18N
        tblRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblRiwayat);

        Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 86, 719, 215));

        jLabel1.setFont(new java.awt.Font("Meiryo UI", 1, 24)); // NOI18N
        jLabel1.setText("Nama Penumpang ");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 24, -1, -1));

        Nama.setFont(new java.awt.Font("Ubuntu Condensed", 0, 14)); // NOI18N
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        Panel.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 29, 271, 31));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        Panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 300));

        jPanel3.add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 790, 320));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Meiryo UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Riwayat Pemesanan");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 53, 320, 76));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102)));

        jPanel8.setBackground(new java.awt.Color(255, 153, 153));

        exit3.setBackground(new java.awt.Color(255, 255, 255));
        exit3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        exit3.setForeground(new java.awt.Color(255, 255, 255));
        exit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit3.setText("X");
        exit3.setMaximumSize(new java.awt.Dimension(64, 64));
        exit3.setMinimumSize(new java.awt.Dimension(64, 64));
        exit3.setPreferredSize(new java.awt.Dimension(64, 64));
        exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit3MousePressed(evt);
            }
        });

        back1.setBackground(new java.awt.Color(255, 255, 255));
        back1.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        back1.setForeground(new java.awt.Color(255, 255, 255));
        back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Long_Arrow_Left_64px.png"))); // NOI18N
        back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                back1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 702, Short.MAX_VALUE)
                .addComponent(exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 138, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 790, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
    public void getData(){
        dataLogin = pm.cariLogin(usr, pass);
        Nama.setText(dataLogin.get(0).getNama());
        Nama.setEditable(false);
        String query;
        try{
            con = db.con;
            
            st = (Statement) con.createStatement();
            
           
           query = "SELECT distinct tiket.tgl_pemesanan, jadwal.hari_tgl, jadwal.jam, \n"
                   + "bus.plat, kursi.id_kursi, rute.asal, rute.tujuan \n"
                   + "from tiket, jadwal, bus, kursi, rute, lintasan, tempat,penumpang \n"
                   + "where tiket.id_jadwal = jadwal.id_jadwal and jadwal.id_lintasan = lintasan.id_lintasan \n"
                   + "and lintasan.Id_Bus = bus.id_bus and lintasan.id_rute = rute.id_rute and  \n"
                   + "tiket.id_tempat = tempat.id_tempat and \n"
                   + "tempat.id_kursi = kursi.id_kursi and tiket.kode_user = penumpang.kode_user and tiket.kode_user = '"+kd_usr+"' ";
           
            
          
            st.executeQuery(query);
            rs = st.executeQuery(query);
           
            
            while(rs.next()){
                Object[] obj = new Object[7];
            
                obj[0] = rs.getString("tgl_pemesanan");
                obj[1] = rs.getString("hari_tgl");
                obj[2] = rs.getString("jam");
                obj[3] = rs.getString("plat");
                obj[4] = rs.getString("id_kursi");
                obj[5] = rs.getString("asal");
                obj[6] = rs.getString("tujuan");
                
                ledom.addRow(obj);
                
            }
             
           
           
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_NamaActionPerformed

    private void exit3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit3MousePressed

    private void back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseClicked
        // TODO add your handling code here:
        dispose();
        Menu_Default md = new Menu_Default();
        md.setVisible(true);
    }//GEN-LAST:event_back1MouseClicked

    private void back1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_back1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat_Pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nama;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel back1;
    private javax.swing.JLabel exit3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRiwayat;
    // End of variables declaration//GEN-END:variables
}
